
name: github
  repo: hugoadmin2.vercel.app/ # Path to your Github/Gitlab repository
  branch: main # Branch to update
  base_url: https://hugoadmin2.vercel.app/


media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false

    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", hint: "文章标题"}
      - {label: "Slug", name: "slug", widget: "string", required: false, hint: "Slug可以是目录,如 linux/archlinux, 此项会作为路径的功能可能会被 path meta 覆盖"}
      - {label: "Comments", name: "comments", widget: "boolean", default: true, hint: "true 允许评论, false 禁止评论"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, hint: "草稿不会 build"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "cover", widget: "image", required: false, hint: "封面图片"}
      - {label: "Tags", name: "tags", widget: "list", required: false, "文章标签，用半角逗号分隔"}
      - {label: "Body", name: "body", widget: "markdown", hint: "博客正文"}
