backend:
  name: github
  repo: waimao365/hugoadmin1 # Path to your Github/Gitlab repository
  branch: main # Branch to update
  base_url: https://hexo-waimao365.vercel.app
  

media_folder: "images/uploads" # 博客上传图片所在的目录

collections:
  - name: "blog" # 用于路径
    label: "Blog" # 用于 UI
    folder: "_posts/" # 博客文章所在的路径
    create: true # 允许创建新文件（必须打开 否则不能新建新文章）
    slug: "---" # 档案名称
    fields: # 修改器可修改的头数据
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
